### ISSUE TITLE
Should AQL query delete not downloaded files regardless of how old they are?

### ISSUE THREAD

**Issue by gangefors** [jfrog/jfrog-cli-plugins#81]
**rt-cleanup**

In the rt-cleanup plugin [the AQL query](https://github.com/jfrog/jfrog-cli-plugins/blob/42d98ef55cde41b056a1604311f4b5290c2a94ac/rt-cleanup/commands/clean.go#L116) used to find artifacts to delete will delete any artifact that haven't been downloaded regardless of the age of the artifact. However, if they have been downloaded they are kept for the specified time.

Personally I find this extremely counter intuitive and files that were just uploaded will be deleted.

I find the following AQL query to better fit how I interpret the plugin is intended to be used (delete artifacts unused for # time).

```
items.find({
    "repo": "my-repo",
    "$or": [
        {
            "$and": [
                {"modified": {"$before": "60d"}},
                {"updated": {"$before": "60d"}},
                {"stat.downloads": {"$eq": null}}
            ]
        },
        {
            "$and": [
                {"modified": {"$before": "60d"}},
                {"updated": {"$before": "60d"}},
                {"stat.downloads": {"$gt": "0"}},
                {"stat.downloaded": {"$before": "60d"}}
            ]
        }
    ]
}).include("stat")

```

**Comment by talarian1** [comment]
Hi @gangefors, 
Thanks for your feedback, I like your approach. 
Would you like to contribute this modification by opening a PR [here](https://github.com/jfrog/jfrog-cli-plugins)?

**Comment by gangefors** [comment]
Sorry that it took so long, but I've created PR #87 now.

**Comment by RobiNino** [comment]
Hi @gangefors ,
rt-cleanup plugin version 1.1.0 was just released and includes this improvement.
Thanks again for your contribution!
