### ISSUE TITLE
jf 2.17.0 breaks rt-cleanup plugin with v6 config

### ISSUE THREAD

**Issue by Fleshgrinder** [jfrog/jfrog-cli-plugins#95]
**CLI plugin name**
rt-cleanup

**Describe the bug**
Commands fail with message `[Error] no server-id was found, or the server-id has no url`

**To reproduce**
Use latest `jf` release which creates a `v6` configuration, in our particular case the following chain of commands leads to the failure:

```bash
jf config add --user user --password pass --url url it
jf config use it
jf rt-cleanup clean --time-unit day --no-dl 7 gradle-build-caches
```

**Expected behavior**
It should just work as it does with `v5` configuration files.

**Versions**
- jf version 2.17.0
- rt-cleanup version v1.1.0

**Additional context**
The following fixes the issue:

```bash
jf config add --user user --password pass --url url it
jf config use it
cp ~/.jfrog/jfrog-cli.conf.v6 ~/.jfrog/jfrog-cli.conf.v5 # 🔥
jf rt-cleanup clean --time-unit day --no-dl 7 gradle-build-caches
```

**Comment by talarian1** [comment]
Hi @Fleshgrinder,
rt-cleanup version v1.1.1 is released and includes a fix for this bug. 
We will appreciate any feedback. 
Thanks!
